name: Install and Run UltimMC

on:
  workflow_dispatch:

jobs:
  setup-ultimmc:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget curl

    - name: Download UltimMC
      run: |
        wget https://nightly.link/UltimMC/Launcher/workflows/main/develop/mmc-cracked-lin64.zip
        unzip mmc-cracked-lin64.zip

    - name: Give Execute Permissions
      run: |
        chmod +x UltimMC/UltimMC  # Adjust this if the executable has a different name

    - name: Start UltimMC
      run: |
        ./UltimMC/UltimMC &  # Start UltimMC in the background

    - name: Set up ngrok for public access
      run: |
        wget https://bin.equinox.io/c/111111/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin
        ngrok http 8080 &  # Replace 8080 with the actual port used by UltimMC

    - name: Output ngrok URL
      run: |
        sleep 10  # Wait for ngrok to initialize
        curl -s http://localhost:4040/api/tunnels | jq '.tunnels[0].public_url'
