name: Cloudflare SSH Tunnel

on: [push]

jobs:
  ssh-tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cloudflared
        run: |
          # Download cloudflared
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          # Move it to /usr/local/bin and make it executable
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
          sudo chmod +x /usr/local/bin/cloudflared

      - name: Start SSH Server
        run: |
          sudo apt-get update && sudo apt-get install openssh-server -y
          sudo service ssh start

      - name: Create Cloudflare Tunnel
        run: |
          cloudflared tunnel --url tcp://localhost:22 &

      - name: Display connection info
        run: echo "SSH tunnel is set up. Connect using your Cloudflare tunnel."
