name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download ngrok
        run: Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      - name: Unzip ngrok
        run: Expand-Archive -Path ngrok.zip -DestinationPath . -Force
      - name: Connect to ngrok
        run: .\ngrok.exe authtoken YOUR_ACTUAL_NGROK_AUTH_TOKEN && .\ngrok.exe tcp 3389
