name: VNC Setup for GUI Access

on:
  workflow_dispatch:

jobs:
  setup-vnc:
    runs-on: ubuntu-latest
    steps:
    - name: Install VNC and XFCE
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xfce4-goodies tightvncserver
        
    - name: Configure VNC
      run: |
        mkdir -p ~/.vnc
        echo "password" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        echo '#!/bin/bash' > ~/.vnc/xstartup
        echo 'xrdb $HOME/.Xresources' >> ~/.vnc/xstartup
        echo 'startxfce4 &' >> ~/.vnc/xstartup
        chmod +x ~/.vnc/xstartup
        
    - name: Start VNC Server
      run: |
        vncserver :1 -geometry 1280x800 -depth 24
        echo "VNC server started on display :1"
        
    - name: Setup SSH Tunnel
      run: |
        echo "To access the VNC server, set up an SSH tunnel with:"
        echo "ssh -L 5901:localhost:5901 -p [SSH_PORT] [SSH_USER]@[SSH_HOST]"
        echo "Then connect your VNC client to localhost:5901"
        echo "VNC Password: password"
        
    - name: Keep Alive
      run: |
        echo "VNC server is running. You can now connect using an SSH tunnel and VNC client."
        echo "This step will timeout after 60 minutes."
        sleep 3600
