name: Temporary SSH-like Access

on:
  workflow_dispatch:

jobs:
  provide-ssh-access:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
      
    - name: Keep alive
      run: |
        echo "SSH-like session is active for 30 minutes."
        echo "You can install software and work in this environment."
        echo "Remember, this environment is temporary and will be destroyed after the workflow ends."
        sleep 1800  # 30 minutes
