name: SSH Access to Runner

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Upterm session
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-actor: true  # Optional, restricts access to only you

    - name: Wait for session
      run: sleep 3600  # Keeps the job running for an hour; adjust as needed
